<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Microsoft.AspNetCore.Identity" />
    <None Remove="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <None Remove="Microsoft.AspNetCore.Identity.UI" />
    <None Remove="Entities\Attributes\" />
    <None Remove="Enums\" />
    <None Remove="Entities\Base %28copy%29\" />
    <None Remove="Entities\DTOs\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Xpo" Version="20.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.21" />
    <PackageReference Include="System.Data.OleDb" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\Attributes\" />
  </ItemGroup>
</Project>
